artifacts_root: artifacts  #root direcotry is artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/syedshamir/-Chicken-Disease-Classification-Projects/raw/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  